### ISSUE TITLE
Set user passwords for docker-compose-lamp

### ISSUE THREAD

**Issue by Ovesta** [a-kom/docker-compose-lamp#6]
Привет Андрей,
Спасибо за LAMP! 
Ты мог бы подсказать, как задать пароли для юзеров? Я пока могу зайти только без пароля в MySQL Shell, но не знаю как зайти в phpmyadmin или использовать MySQL Workbench клиент

**Comment by akhomy** [comment]
Привет, посмотри в файле `docker-compose.yml` строки 
```
environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: testdrive
            MYSQL_PASSWORD: testdrive
            MYSQL_DATABASE: testdrive
```
Где, MYSQL_USER - пользователь MySQL, MYSQL_PASSWORD - пароль пользователя, MYSQL_DATABASE - имя базы данных MySQL, MYSQL_ROOT_PASSWORD - пароль root пользователя MySQL. Эти переменные создаются и заполняются при создание docker контейнеров. Более подробно - [MySQL Docker Image](https://hub.docker.com/_/mysql/), заголовок - **Environment Variables**.
